
nationalHolidays = []
nationalHolidays.append("01-01") #Ano Novo
nationalHolidays.append("Data Móvel") 	#Sexta-feira Santa + Páscoa + Segunda Feira
nationalHolidays.append("04-25") #Revolução dos Cravos
nationalHolidays.append("05-01") #Dia do Trabalho
nationalHolidays.append("06-10") #Dia de Portugal, de Camões e das Comunidades Portuguesas
nationalHolidays.append("Data Móvel") 	#Corpo de Deus
nationalHolidays.append("08-15")#Assunção de Nossa Senhora
nationalHolidays.append("10-05") #Proclamação da República
nationalHolidays.append("11-01") #Dia de Todos os Santos
nationalHolidays.append("12-01") #Restauração da Independência
nationalHolidays.append("12-08") #Dia da Imaculada Conceição
nationalHolidays.append("12-25") #Natal

regionalHolidays = []
regionalHolidays.append(("01-11", "Obidos")) # ver se acentos dão match
regionalHolidays.append(("01-13", "Cadaval"))
regionalHolidays.append(("01-13", "Santa Maria de Penaguião")) # ver se acentos dão match
regionalHolidays.append(("01-13", "Viana do Alentejo"))
regionalHolidays.append(("01-13", "Vila Nova de Poiares"))
regionalHolidays.append(("01-14", "Elvas"))
regionalHolidays.append(("01-15", "Santa Cruz"))
regionalHolidays.append(("01-20", "Santa Maria da Feira"))
regionalHolidays.append(("01-22", "São Vicente")) # ver se acentos dão match
regionalHolidays.append(("01-22", "Vila do Bispo"))

regionalHolidays.append(("02-02", "Mourão")) # ver se acentos dão match
regionalHolidays.append(("02-10", "Aguiar da Beira"))
regionalHolidays.append(("02-18", "Valença")) # ver se acentos dão match

regionalHolidays.append(("03-01", "Tomar"))
regionalHolidays.append(("03-02", "Vila Nova de Paiva"))
regionalHolidays.append(("03-04", "Manteigas"))
regionalHolidays.append(("03-05", "Ferreira do Alentejo"))
regionalHolidays.append(("03-08", "Montemor-o-Novo")) # ver se acentos dão match
regionalHolidays.append(("03-12", "Monção")) # ver se acentos dão match
regionalHolidays.append(("03-19", "Póvoa de Lanhoso")) # ver se acentos dão match
regionalHolidays.append(("03-19", "Santarém")) # ver se acentos dão match
regionalHolidays.append(("03-19", "Torre de Moncorvo"))
regionalHolidays.append(("03-19", "Vizela"))

regionalHolidays.append(("04-02", "Alpiarça")) # ver se acentos dão match
regionalHolidays.append(("04-06", "Fronteira"))
regionalHolidays.append(("04-11", "Lagoa")) # ver se acentos dão match
regionalHolidays.append(("04-23", "Velas"))
regionalHolidays.append(("04-26", "Belmonte"))

regionalHolidays.append(("05-02", "Arouca"))
regionalHolidays.append(("05-03", "Barcelos"))
regionalHolidays.append(("05-03", "Sernancelhe"))
regionalHolidays.append(("05-04", "Sesimbra"))
regionalHolidays.append(("05-08", "Murça"))
regionalHolidays.append(("05-12", "Aveiro"))
regionalHolidays.append(("05-13", "Vila Real de Santo António"))
regionalHolidays.append(("05-14", "Vouzela"))
regionalHolidays.append(("05-15", "Caldas da Rainha"))
regionalHolidays.append(("05-16", "Fafe"))
regionalHolidays.append(("05-20", "Vinhais"))
regionalHolidays.append(("05-21", "Vila Nova de Foz Côa"))
regionalHolidays.append(("05-22", "Leiria"))
regionalHolidays.append(("05-23", "Celorico da Beira"))
regionalHolidays.append(("05-23", "Portalgre"))
regionalHolidays.append(("05-25", "Mirandela"))
regionalHolidays.append(("05-25", "Santana"))
regionalHolidays.append(("05-29", "Trancoso"))
#29 de Maio é feriado regional dos açores?

regionalHolidays.append(("06-01", "Palmela"))
regionalHolidays.append(("06-01", "Miranda do Corvo"))
regionalHolidays.append(("06-01", "São Brás de Alportel"))
regionalHolidays.append(("06-07", "Oeiras"))
regionalHolidays.append(("06-09", "Montalegre"))
regionalHolidays.append(("06-13", "Aljustrel"))
regionalHolidays.append(("06-13", "Alvaiázere"))
regionalHolidays.append(("06-13", "Amares"))
regionalHolidays.append(("06-13", "Cascais"))
regionalHolidays.append(("06-13", "Estarreja"))
regionalHolidays.append(("06-13", "Ferreira do Zêzere"))
regionalHolidays.append(("06-13", "Lisboa"))
regionalHolidays.append(("06-13", "Proença-a-Nova"))
regionalHolidays.append(("06-13", "Reguengos de Monsaraz"))
regionalHolidays.append(("06-13", "Vale de Cambra"))
regionalHolidays.append(("06-13", "Vila Nova da Barquinha"))
regionalHolidays.append(("06-13", "Vila Nova de Famalicão"))
regionalHolidays.append(("06-13", "Vila Real"))
regionalHolidays.append(("06-13", "Vila Verde"))
regionalHolidays.append(("06-14", "Abrantes"))
regionalHolidays.append(("06-16", "Espinho"))
regionalHolidays.append(("06-16", "Olhão"))
regionalHolidays.append(("06-17", "Castanheira de Pera"))
regionalHolidays.append(("06-20", "Corvo"))
regionalHolidays.append(("06-20", "Ourém"))
regionalHolidays.append(("06-22", "Vila Pouca de Aguiar"))
regionalHolidays.append(("06-24", "Alcácer do Sal"))
regionalHolidays.append(("06-24", "Alcochete"))
regionalHolidays.append(("06-24", "Almodôvar"))
regionalHolidays.append(("06-24", "Angra do Heroismo"))
regionalHolidays.append(("06-24", "Armamar"))
regionalHolidays.append(("06-24", "Arronches"))
regionalHolidays.append(("06-24", "Braga"))
regionalHolidays.append(("06-24", "Calheta"))
regionalHolidays.append(("06-24", "Castelo de Paiva"))
regionalHolidays.append(("06-24", "Castro Marim"))
regionalHolidays.append(("06-24", "Cinfães"))
regionalHolidays.append(("06-24", "Figueira da Foz"))
regionalHolidays.append(("06-24", "Figueiró dos Vinhos"))
regionalHolidays.append(("06-24", "Guimarães"))
regionalHolidays.append(("06-24", "Horta"))
regionalHolidays.append(("06-24", "Lourinhã"))
regionalHolidays.append(("06-24", "Lousã"))
regionalHolidays.append(("06-24", "Mértola"))
regionalHolidays.append(("06-24", "Moimenta da Beira"))
regionalHolidays.append(("06-24", "Moura"))
regionalHolidays.append(("06-24", "Nelas"))
regionalHolidays.append(("06-24", "Porto"))
regionalHolidays.append(("06-24", "Porto Santo"))
regionalHolidays.append(("06-24", "Santa Cruz das Flores"))
regionalHolidays.append(("06-24", "São João da Pesqueira"))
regionalHolidays.append(("06-24", "Sertã"))
regionalHolidays.append(("06-24", "Tabuaço"))
regionalHolidays.append(("06-24", "Tavira"))
regionalHolidays.append(("06-24", "Valongo"))
regionalHolidays.append(("06-24", "Vila de Conde"))
regionalHolidays.append(("06-24", "Vila do Porto"))
regionalHolidays.append(("06-24", "Vila Franca do Campo"))
regionalHolidays.append(("06-24", "Vila Nova de Gaia"))
regionalHolidays.append(("06-28", "Barreiro"))
regionalHolidays.append(("06-29", "Alfândega da Fé"))
regionalHolidays.append(("06-29", "Bombarral"))
regionalHolidays.append(("06-29", "Castro Daire"))
regionalHolidays.append(("06-29", "Castro Verde"))
regionalHolidays.append(("06-29", "Évora"))
regionalHolidays.append(("06-29", "Felgueiras"))
regionalHolidays.append(("06-29", "Lajes do Pico"))
regionalHolidays.append(("06-29", "Macedo de Cavaleiros"))
regionalHolidays.append(("06-29", "Montijo"))
regionalHolidays.append(("06-29", "Penedono"))
regionalHolidays.append(("06-29", "Porto de Mós"))
regionalHolidays.append(("06-29", "Póvoa de Varzim"))
regionalHolidays.append(("06-29", "Ribeira Brava"))
regionalHolidays.append(("06-29", "Ribeira Grande"))
regionalHolidays.append(("06-29", "São Pedro do Sul"))
regionalHolidays.append(("06-29", "Seixal"))
regionalHolidays.append(("06-29", "Sintra"))

#1 de Julho é feriado regional da madeira?
regionalHolidays.append(("07-02", "Almeida"))
regionalHolidays.append(("07-03", "Seia"))
regionalHolidays.append(("07-04", "Castenheira de Pera"))
regionalHolidays.append(("07-04", "Coimbra"))
regionalHolidays.append(("07-07", "Figueira de Castelo Rodrigo"))
regionalHolidays.append(("07-08", "Amarante"))
regionalHolidays.append(("07-08", "Chaves"))
regionalHolidays.append(("07-10", "Miranda do Douro"))
regionalHolidays.append(("07-11", "Arcos de Valdevez"))
regionalHolidays.append(("07-11", "Santo Tirso"))
regionalHolidays.append(("07-17", "Paredes"))
regionalHolidays.append(("07-17", "Penacova"))
regionalHolidays.append(("07-18", "Nordeste"))
regionalHolidays.append(("07-22", "Madalena"))
regionalHolidays.append(("07-22", "Porto Moniz"))
regionalHolidays.append(("07-22", "Condeixa-a-Nova"))
regionalHolidays.append(("07-22", "Pedrógão Grande"))
regionalHolidays.append(("07-25", "Cantanhede"))
regionalHolidays.append(("07-25", "Celourico de Basto"))
regionalHolidays.append(("07-25", "Mira"))
regionalHolidays.append(("07-25", "Mondim de Basto"))
regionalHolidays.append(("07-25", "Ovar"))
regionalHolidays.append(("07-25", "Santiago do Cacém"))
regionalHolidays.append(("07-26", "Loures"))

regionalHolidays.append(("08-10", "Paredes de Coura"))
regionalHolidays.append(("08-10", "Vimioso"))
regionalHolidays.append(("08-11", "Praia da Viória"))
regionalHolidays.append(("08-13", "Góis"))
regionalHolidays.append(("08-14", "Batalha"))
regionalHolidays.append(("08-16", "Peso da Régua"))
regionalHolidays.append(("08-14", "Ribeira de Pena"))
regionalHolidays.append(("08-14", "São Roque do Pico"))
regionalHolidays.append(("08-14", "Vila Viçosa"))
regionalHolidays.append(("08-17", "Coruche"))
regionalHolidays.append(("08-19", "Esposende"))
regionalHolidays.append(("08-20", "Albufeira"))
regionalHolidays.append(("08-20", "Alcobaça"))
regionalHolidays.append(("08-20", "Sátão"))
regionalHolidays.append(("08-20", "Viana do Castelo"))
regionalHolidays.append(("08-20", "Albergaria-a-Velha"))
regionalHolidays.append(("08-21", "Funchal"))
regionalHolidays.append(("08-22", "Bragança"))
regionalHolidays.append(("08-24", "Baião"))
regionalHolidays.append(("08-24", "Ponte da Barca"))
regionalHolidays.append(("08-24", "Vila Flor"))
regionalHolidays.append(("08-25", "Penalva do Castelo"))
regionalHolidays.append(("08-25", "Pinhel"))
regionalHolidays.append(("08-28", "Barrancos"))
regionalHolidays.append(("08-29", "Aljezur"))

regionalHolidays.append(("09-03", "Silves"))
regionalHolidays.append(("09-07", "Arganil"))
regionalHolidays.append(("09-07", "Faro"))
regionalHolidays.append(("09-07", "Vendas Novas"))
regionalHolidays.append(("09-08", "Alcoutim"))
regionalHolidays.append(("09-08", "Lagoa"))
regionalHolidays.append(("09-08", "Lamego"))
regionalHolidays.append(("09-08", "Mangualde"))
regionalHolidays.append(("09-08", "Marco de Canaveses"))
regionalHolidays.append(("09-08", "Marvão"))
regionalHolidays.append(("09-08", "Montemor-o-Velho"))
regionalHolidays.append(("09-08", "Murtosa"))
regionalHolidays.append(("09-08", "Nazaré"))
regionalHolidays.append(("09-08", "Odemira"))
regionalHolidays.append(("09-08", "Ourique"))
regionalHolidays.append(("09-08", "Ponta de Sol"))
regionalHolidays.append(("09-08", "Sabrosa"))
regionalHolidays.append(("09-11", "Amadora"))
regionalHolidays.append(("09-15", "Fundão"))
regionalHolidays.append(("09-15", "Setúbal"))
regionalHolidays.append(("09-16", "Tondela"))
regionalHolidays.append(("09-19", "Vila de Rei"))
regionalHolidays.append(("09-20", "Ponte de Lima"))
regionalHolidays.append(("09-21", "Sever do Vouga"))
regionalHolidays.append(("09-21", "Soure"))
regionalHolidays.append(("09-21", "Viseu"))
regionalHolidays.append(("09-22", "Sardoal"))
regionalHolidays.append(("09-29", "Cabeceiras de Basto"))
regionalHolidays.append(("09-29", "Fornos de Algodres"))
regionalHolidays.append(("09-29", "Penela"))
regionalHolidays.append(("09-29", "Resende"))
regionalHolidays.append(("09-29", "Tarouca"))

regionalHolidays.append(("10-01", "Vila Nova de Cerveira"))
regionalHolidays.append(("10-07", "Oliveira de Frades"))
regionalHolidays.append(("10-07", "Oliveira do Hospital"))
regionalHolidays.append(("10-09", "Machico"))
regionalHolidays.append(("10-11", "São João da Madeira"))
regionalHolidays.append(("10-15", "Mogadouro"))
regionalHolidays.append(("10-16", "Câmara de Lobos"))
regionalHolidays.append(("10-20", "Covilhã"))
regionalHolidays.append(("10-20", "Terras de Bouro"))
regionalHolidays.append(("10-22", "Grândola"))
regionalHolidays.append(("10-27", "Lagos"))

regionalHolidays.append(("11-06", "Boticas"))
regionalHolidays.append(("11-06", "Paços de Ferreira"))
regionalHolidays.append(("11-06", "Rio Maior"))
regionalHolidays.append(("11-06", "Valpaços"))
regionalHolidays.append(("11-11", "Alijó"))
regionalHolidays.append(("11-11", "Mêda"))
regionalHolidays.append(("11-11", "Penafiel"))
regionalHolidays.append(("11-11", "Pombal"))
regionalHolidays.append(("11-11", "Torres Vedras"))
regionalHolidays.append(("11-19", "Odivelas"))
regionalHolidays.append(("11-19", "Trofa"))
regionalHolidays.append(("11-23", "Gavião"))
regionalHolidays.append(("11-24", "Entroncamento"))
regionalHolidays.append(("11-24", "Sines"))
regionalHolidays.append(("11-25", "Calheta"))
regionalHolidays.append(("11-27", "Guarda"))
regionalHolidays.append(("11-30", "Mesão Frio"))

regionalHolidays.append(("12-11", "Portimão"))
regionalHolidays.append(("12-26", "Madeira"))
#26 de Dezembro é feriado regional da madeira?
